"use strict";
exports.__esModule = true;
var pez_1 = require("./pez");
var gato_1 = require("./gato");
var ara_a_1 = require("./ara\u00F1a");
var listaAnimales_1 = require("./listaAnimales");
var gato1 = new gato_1.Gato(4, "minino");
var arana1 = new ara_a_1.Arana(8);
var juanito = new pez_1.Pez(4, "Doris");
var gato2 = new gato_1.Gato(4, "catara");
var animales1 = new listaAnimales_1.ListaAnimales();
animales1.agregarAnimal(gato1);
animales1.agregarAnimal(arana1);
animales1.agregarAnimal(juanito);
console.log(animales1.buscar(juanito));
console.log(animales1);
animales1.removerAnimal(juanito);
console.log(animales1);
juanito.setIntPtas(0);
console.log(juanito.getIntPatas());
arana1.caminar(8);
gato1.jugar(gato1.getNombre());
gato2.jugar(gato2.getNombre());
animales1.agregarAnimal(gato2);
console.log(animales1);
